//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Desktop_Scrapping.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category_Table
    {
        public int CategoryID { get; set; }
        public string Category_Name { get; set; }
        public int ID_Category { get; set; }
    }
}
