//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Desktop_Scrapping.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemsName
    {
        public int ID { get; set; }
        public string ItemsName1 { get; set; }
        public Nullable<int> ScrapID { get; set; }
        public string ItemUrl { get; set; }
    
        public virtual ScrapDataTime ScrapDataTime { get; set; }
    }
}
