//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Desktop_Scrapping.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScrapDataTime
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ScrapDataTime()
        {
            this.ItemsNames = new HashSet<ItemsName>();
            this.SellerNameScrapes = new HashSet<SellerNameScrape>();
        }
    
        public int ScrapID { get; set; }
        public string TimeDates { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemsName> ItemsNames { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SellerNameScrape> SellerNameScrapes { get; set; }
    }
}
